name: Development deployment
on:
    push:
        branches:
          - develop
jobs:
    Vercel:
        if: ${{ vars.DEPLOY_PROVIDER == 'vercel' }}
        uses: ./.github/workflows/deploy_vercel.yaml
        secrets: inherit
        with:
            environment: preview
